version: "3.1"
nlu:
- intent: just_rating
  examples: |
    - at least [seven](rating)
    - [8](rating)
    - [4](rating)
    - [three](rating) is enough.
- intent: recommendation_without_movie_over_informative
  examples: |
    - Do you have any movie suggestions? I'm interested in watching a [horror](genre) movie, and it would be awesome if [Johnny Depp](cast) starred in it. Also, I prefer movies released in 2020.
    - can you recommend me a movie? I would like it to be an [horror](genre) movie with [Johnny Depp](cast) as an actor. I would like also to be released in [2020](release_date).
    - Could you suggest a movie for me? I'm in the mood for a [horror](genre) film featuring [Johnny Depp](cast) as one of the actors. It would be great if it was released in [2020](release_date).
- intent: movie_genre+movie_producer
  examples: |
    - I'm looking for some information on [Saw II](movie_name)'s genre and producer. Can you assist me?
    - Would you happen to know the genre and producer of [The Martian](movie_name)?
    - Can you provide me with the genre and producer of [Gravity](movie_name), please?
    - What is the genre and producer of [Jurassic Park](movie_name)? I'd appreciate it if you could tell me.
- intent: greetings
  examples: |
    - Hi
    - good afternoon
    - moin
    - hi
    - goodevening
- intent: is_after
  examples: |
    - If it's possible, [after this year ends](movie_period)
    - [Following the conclusion of this year](movie_period), if attainable
    - [In the next year](movie_period)
    - [After the current year](movie_period) concludes
- intent: is_before
  examples: |
    - [Prior](movie_period) to the current year
    - If it can be done, [prior](movie_period) to this year
    - [Before](movie_period) the current calendar year
    - [Prior](movie_period) to the start of this year
- intent: just_rating+just_director
  examples: |
    - [5](rating) if you can. Moreover, is it within the realm of possibility for me to suggest [Martin Scorsese](director_name) as the director?
    - [six](rating). Also, can I have [Taika Waititi](director_name) as the director for it?
    - rated [2](rating) and directed by [Martin Scorsese](director_name).
    - [8](rating). Also can I have [Dario Argento](director_name) as director in it?
    - [7](rating). I also would like to have [Dario Argento](director_name) as director.
- intent: is_exactly
  examples: |
    - If within the realm of possibility, [this year](movie_period)
    - If it is viable, [during the present year](movie_period)
    - Ideally [during this year](movie_period)
    - [Within the bounds of the current year](movie_period)
    - [exactly](movie_period) this year
- intent: deny
  examples: |
    - not really
    - No, I want to make a change
    - no way
    - no, I'm fine
    - don't like that
    - No, thank you.
- intent: ask_recommendation_without_movie
  examples: |
    - Can you give me a movie recommendation?
    - Can you recommend a movie with great cinematography?
    - I'm looking for a movie to watch, do you have any suggestions?
    - What's a movie you'd recommend for a rainy day?
    - Could you recommend a movie that's set in a specific time period?
    - Do you have any recommendations for a movie to watch?
- intent: affirm
  examples: |
    - y
    - yes, please
    - yeah all is good
    - Yes, please!
    - yes please
    - all good
    - Absolutely!
    - Absolutely, yes!
- intent: just_genre+just_cast+just_year
  examples: |
    - [Comedy-horror](genre). It would be hilarious to see [Sandra Bullock](cast) in the movie, and I prefer the movie to be released in [1997](release_date).
    - [Romantic comedy](genre). I would also like to have [Jennifer Lawrence](cast) as an actress, and I would like the movie to be released in [2005](release_date).
    - I'm in the mood for a [horror](genre) film, if it's possible to find one. It would be fantastic to have [Brad Pitt](cast) as the actor. Additionally, can the movie be released in [2020](release_date)?
    - [Adventure](genre). I would also like to have [Chris Hemsworth](cast) as an actor, and I would like the movie to be released in [2014](release_date).
    - I'm specifically interested in [horror](genre) movies, if there are any available. It would be fantastic to have [Brad Pitt](cast) as the actor. Furthermore, can the movie be released in [2020](release_date)?
    - [Thriller](genre). I would also like to have [Leonardo DiCaprio](cast) as an actor, and I would like the movie to be released in [2019](release_date).
    - [Sci-fi](genre). I would also like to have [Tom Hanks](cast) as an actor, and I would like the movie to be released in [2021](release_date).
- intent: movie_rating
  examples: |
    - What are the factors that influenced the movie's rating?
    - How did the rating impact the movie's marketing and promotion?
    - How did audiences and critics rate [Forrest Gump](movie_name)?
    - What was the critical response to the movie's rating?
    - How did audiences and critics rate [The Matrix](movie_name)?
    - What was the impact of the movie's rating on its overall success or reception?
    - I'm curious, what's the general opinion of [Jurassic Park](movie_name)?
    - Can you inform me of the overall rating of [Back to the Future](movie_name)?
    - What is the movie's overall rating?
- intent: movie_runtime
  examples: |
    - Can you tell me how many minutes the movie is?
    - Can you give me the duration of [Indiana Jones and the Raiders of the Lost Ark](movie_name)?
    - What's the runtime of [Back to the Future](movie_name)?
    - How long is [Pulp Fiction](movie_name)?
    - How much time does the movie require?
    - Do you happen to know the length of [The Dark Knight](movie_name)?
    - How long does the movie last?
    - How much time does [Forrest Gump](movie_name) take up?
- intent: movie_revenue
  examples: |
    - What was the distribution revenue of the movie?
    - Can you tell me about any long-term revenue streams related to the movie, such as home video sales or merchandise?
    - Do you know the box office revenue for [Black Panther](movie_name)?
    - What was the total earnings for [The Avengers](movie_name)?
    - Can you inform me of the financial success of [Titanic](movie_name)?
    - How successful was the movie at the box office?
    - Could you provide more information about the movie's revenue?
    - What is the total revenue generated by the movie?
    - What is the overall financial success of the movie?
- intent: out_of_scope
  examples: |
    - Can you recommend a good hiking trail?
    - Can you give me tips on public speaking?
    - Can you recommend a good gym?
    - Can you help me with my math homework?
    - Who won the Super Bowl last year?
    - How can I improve my photography skills?
    - What's the recipe for spaghetti carbonara?
    - What's the best way to invest money?
- intent: ask_recommendation_with_movie
  examples: |
    - After watching [The Big Lebowski](movie_name), what other movies would you suggest?
    - What other movies would you suggest if I liked [A Beautiful Mind](movie_name)?
    - I just watched [The Thing](movie_name), do you know any movies that are similar?
    - Can you suggest any movies similar to [One Flew Over the Cuckoo's Nest](movie_name)?
    - I just watched [A Clockwork Orange](movie_name), do you know any movies that are similar?
    - Do you know any movies that are similar to [Forrest Gump](movie_name)?
    - What other movies would you suggest if I liked [American History X](movie_name)?
    - I recently watched [No Country for Old Men](movie_name), do you know any movies that are similar?
    - I just saw [The Matrix](movie_name), do you have any similar movie recommendations?
- intent: goodbye
  examples: |
    - Affirmative, see you later.
    - Cool, catch you later.
    - Understood, bye for now.
    - ok perfect, bye
    - good night
    - Gotcha, see you later.
    - Fine with me, goodbye for now.
    - Alright, see you later.
- intent: just_genre
  examples: |
    - can I have a [horror](genre) movie
    - [Biopic](genre) with [Drama](genre) elements
    - [Drama](genre), [Romance](genre)
    - [fantasy](genre)
    - [horror](genre)
    - [crime](genre)
    - [documentary](genre)
    - [Sports](genre) with also [Drama](genre)
    - I would like a [horror](genre) movie
- intent: just_year
  examples: |
    - [1980](release_date)
    - in [2006](release_date)
    - [2010](release_date)
    - [2001](release_date)
    - [2021](release_date)
    - [2002](release_date)
    - [2005](release_date)
    - [2000](release_date)
    - find something in [2020](release_date)
- intent: ask_movie_question
  examples: |
    - What types of queries are appropriate?
    - I'd appreciate the opportunity to ask some questions about movies.
    - What is the scope of questions that I can present?
    - I'm hoping to ask questions specifically about movies.
    - May I ask a few questions about movies?
    - I'm curious and would like to ask some questions about movies.
    - I'm eager to ask some questions about movies if that's okay.
    - I'd like to pose some questions that pertain to movies.
    - Are there any restrictions on the nature of questions I can ask?
    - I have some questions about the cinema that I'd like to inquire about.
    - I'd like to ask some questions that are related to the world of movies.
- intent: movie_budget
  examples: |
    - What was the total budget for [The Matrix](movie_name)?
    - Can you tell me the production budget for [The Avengers](movie_name)?
    - What was the total budget for [Indiana Jones and the Raiders of the Lost Ark](movie_name)?
    - [The Amazing Spider-Man](movie_name), what was the production budget for this movie?
    - What was the movie's funding source?
    - What was the budget for [The Avengers: Age of Ultron](movie_name)?
    - How much did it cost to produce the movie?
    - Can you give me some details about the movie's financing?
    - How much did [E.T. the Extra-Terrestrial](movie_name) cost to make?
    - How much did [The Lion King](movie_name) cost to make?
    - What was the total budget for [Rocky](movie_name)?
- intent: movie_composer
  examples: |
    - [Amélie](movie_name), who composed the music for this film?
    - Who was the composer of [Back to the Future](movie_name)?
    - Can you tell me who is the composer of [Titanic](movie_name)?
    - Can you tell me about the composer's previous work?
    - Who composed the music for [Jurassic Park](movie_name)?
    - Can you tell me who is the composer of [Schindler's List](movie_name)?
    - Who composed the music for [Inception](movie_name)?
    - Who composed the music for [The Exorcist](movie_name)?
    - Could you tell me about the film's composer?
    - [The Empire Strikes Back](movie_name), who composed the music for this film?
    - [Scream](movie_name), who composed the music for this film?
    - Who is the composer of [Schindler's List](movie_name)?
    - [Ghostbusters](movie_name), who was the composer of this film?
- intent: ask_movie_with_similar_plot
  examples: |
    - If I give you a plot, would you be able to recommend a movie?
    - If I tell you the plot, could you suggest a good movie to watch?
    - Can you help me find a movie with a storyline that's similar to the plot I'm about to describe?
    - If I describe a plot, could you recommend a movie with a similar storyline?
    - If I tell you the plot, can you recommend a movie with a similar plotline?
    - i have a plot in mind can you recommend me a movie with a similar one
    - If I tell you the plot, could you suggest a movie with a similar storyline?
    - Is there a possibility that you could suggest a movie with a similar plot if I tell you the story?
    - I'm interested in watching a movie that talks about. do you have any suggestions?
    - Is it possible for me to describe a plot and you suggest a movie with a similar one?
    - If I give you a plot, could you recommend a movie with a comparable story?
    - Is there a chance you could suggest a movie with a plot similar to the one I'm describing?
- intent: just_cast
  examples: |
    - [Saoirse Ronan](cast)
    - [Meryl Streep](cast) and [Johnny Depp](cast)
    - [Charlize Theron](cast), [Matt Damon](cast)
    - [Charlize Theron](cast) and [Bill Murray](cast)
    - [Emma Stone](cast)
    - [Gwyneth Paltrow](cast)
    - Is it ok if I ask you [Denzel Washington](cast)?
    - [Ryan Gosling](cast)
    - [Ben Affleck](cast)
    - [Angelina Jolie](cast)
    - [Natalie Portman] and possibly [Diane Keaton](cast)
    - [Harrison Ford](cast)
    - [Tom Cruise](cast)
- intent: movie_producer
  examples: |
    - Can you tell me who produced [The Truman Show](movie_name)?
    - Can you provide more details about the people behind the movie's production?
    - Can you find out who produced [The Shining](movie_name)?
    - I'm curious, who produced [The Graduate](movie_name)?
    - Who was the producer of [Jaws](movie_name)?
    - Do you know who produced [The Godfather Part III](movie_name)?
    - I'm curious, who produced [The Elephant Man](movie_name)?
    - Who put together the movie's production team?
    - Who was in charge of producing the movie?
    - Who produced [A Clockwork Orange] (movie_name)?
    - Who produced [Goodfellas](movie_name)?
    - Do you know who produced [The Godfather](movie_name)?
    - Who produced [The Social Network](movie_name)?
- intent: just_director
  examples: |
    - [Danny Boyle](director_name)
    - [J.J. Abrams](director_name)
    - [Darren Aronofsky](director_name)
    - [Alejandro González Iñárritu](director_name)
    - [David Fincher](director_name)
    - [Bernardo Bertolucci](director_name)
    - I would like [Wong Kar-wai](director_name)
    - [Kathryn Bigelow](director_name)
    - I prefer [Ethan Coen](director_name), if possible
    - [George Lucas](director_name)
    - [Spike Lee](director_name)
    - [Sergio Leone](director_name)
    - [Joe Russo](director_name)
    - [Martin Scorsese](director_name) and [Robert De Niro](director_name)
- intent: movie_plot
  examples: |
    - What is the movie's premise?
    - What is the movie's storyline or narrative arc?
    - What is [The Big Lebowski](movie_name) about?
    - What is [The Dark Knight](movie_name) about?
    - [The Shining](movie_name), can you describe the plot of this movie?
    - What is [The Truman Show](movie_name) about?
    - [Star Wars: Episode V - The Empire Strikes Back](movie_name), can you describe the plot of this movie?
    - What is [Fight Club](movie_name) about?
    - What is [Titanic](movie_name) about?
    - [The Shawshank Redemption](movie_name), what is the plot of this movie?
    - What is [Good Will Hunting](movie_name) about?
    - What is the movie's main storyline?
    - What is the movie's central conflict?
    - its plot
- intent: movie_release_date
  examples: |
    - Can you tell me the release date of [Gladiator](movie_name)?
    - and what about the release date?
    - [The Silence of the Lambs](movie_name), when was this movie released?
    - Can you provide information about any delays in the movie's release?
    - When was [The Prestige](movie_name) released?
    - When was [The Dark Knight Rises](movie_name) released?
    - Can you tell me when [The Silence of the Lambs](movie_name) was released?
    - Can you tell me when the film was released?
    - Can you tell me when [The Shining](movie_name) premiered?
    - Can you tell me the release date for [Star Wars: Episode IV - A New Hope](movie_name)?
    - [The Lord of the Rings: The Fellowship of the Ring](movie_name), what is the release date of this movie?
    - When was [The Truman Show](movie_name) released?
    - When did the movie premiere?
    - When was [The Matrix](movie_name) released?
- intent: movie_genre
  examples: |
    - How would you categorize [Black Panther](movie_name) in terms of genre?
    - Do you know the gnere of [The Princess Bride](movie_name)?
    - Can you tell me the movie's category?
    - Can you give me an idea of the genre of [The Lion King 1½](movie_name)?
    - ok and can you tell me the genre of [Inception](movie_name)?
    - Can you tell me the genre of [Toy Story 3](movie_name)?
    - Do you know the genre of [The Little Mermaid](movie_name)?
    - What category does it fall under?
    - What genre would you classify [The Hunchback of Notre Dame](movie_name) as?
    - What is the movie's classification in terms of genre?
    - Can you inform me of the genre of [The Silence of the Lambs](movie_name)?
    - What is the nature of the movie?
    - Would you classify [The Terminator](movie_name) as a [sci-fi](genre) or an [action](genre) movie?
    - Nice, thank you! can you tell me also about its genre?
- intent: movie_director
  examples: |
    - Can you tell me who directed [The Matrix](movie_name)?
    - Who directed [Apocalypse Now](movie_name)?
    - Can you tell me who directed [The Lion King](movie_name)?
    - Who was in charge of directing the movie?
    - Can you tell me who directed [Back to the Future](movie_name)?
    - Who directed [Gladiator](movie_name)?
    - Can you tell me who directed [The Exorcist](movie_name)?
    - [2001: A Space Odyssey](movie_name), who directed this film?
    - Do you know who directed [Forrest Gump](movie_name)?
    - Who was the director of [The Social Network](movie_name)?
    - [The Departed](movie_name), who was the director of this film?
    - [The Godfather](movie_name), who was the director of this film?
    - Who was the director of [The Thing](movie_name)?
    - What is the director's name?
    - Can you tell me the name of the film's director?
- intent: movie_cast
  examples: |
    - Who are the actors in [The Silence of the Lambs](movie_name)?
    - Who put together the movie's cast?
    - Could you please inform me of [2](number_of_actors) actors that starred in the movie?
    - Who is credited with acting in the movie?
    - [The Lord of the Rings: The Two Towers](movie_name), who stars in this movie?
    - Can you tell me who stars in [Jurassic Park](movie_name)?
    - Can you enlighten me on [twelve](number_of_actors) actors that are in the movie?
    - [The Departed](movie_name), who is part of the cast in this movie?
    - Who stars in [Goodfellas](movie_name)?
    - Who are the actors in [Back to the Future](movie_name)?
    - Can you tell me who stars in [The Matrix](movie_name)?
    - Can you name some of the actors in [Gladiator](movie_name)?
    - [Star Wars: Episode IV - A New Hope](movie_name), who are the actors in this movie?
    - Would you be able to name [5](number_of_actors) actors that appear in the movie?
    - [The Dark Knight Rises](movie_name), who is in the cast of this movie?
    - Who are the main actors in the movie?
    - can you tell me [8](number_of_actors) actor for this movie?
    - Can you tell me who stars in [The Exorcist](movie_name)?
    - how about you tell me [6](number_of_actors) actors for this movie.
- synonym: '1'
  examples: |
    - one
    - One
- synonym: '2'
  examples: |
    - two
    - Two
- synonym: '3'
  examples: |
    - three
    - Three
- synonym: '4'
  examples: |
    - four
    - Four
- synonym: '5'
  examples: |
    - five
    - Five
- synonym: '6'
  examples: |
    - six
    - Six
- synonym: '7'
  examples: |
    - seven
    - Seven
- synonym: '8'
  examples: |
    - eight
    - Eight
- synonym: '9'
  examples: |
    - nine
    - Nine
- synonym: '10'
  examples: |
    - ten
    - Ten
- synonym: horror
  examples: |
    - scary
- synonym: comedy
  examples: |
    - funny
