# The config recipe.
recipe: default.v1

# Configuration for Rasa NLU.
language: en

pipeline:
  - name: SpacyNLP
    model: en_core_web_md
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  # - name: DucklingHttpExtractor
  #   url: "http://localhost:8000"
  #   dimensions: ["time", "number", "amount-of-money", "distance"]
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: yes
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50


# Configuration for Rasa Core.
policies:
  - name: TEDPolicy
    max_history: 8
    epochs: 20
    constrain_similarities: yes
   - name: UnexpecTEDIntentPolicy
    epochs: 20
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.3
   - name: AugmentedMemoizationPolicy
    max_history: 4
  - name: RulePolicy
  
