version: "3.1"
nlu:
- intent: just_rating
  examples: |
    - [10](rating)
    - [1](rating)
    - I would like [five](rating)
    - [9](rating)
- intent: recommendation_without_movie_over_informative
  examples: |
    - Can you suggest a movie for me? I'm in the mood for a [horror](genre) film and would love to see [Johnny Depp](cast) as one of the actors. It would be great if it was released in [2020](release_date).
    - Do you have any movie suggestions? I'm in the mood for a [horror](genre) film and would like [Johnny Depp](cast) to be part of the cast. It would be ideal if it was released in [2020](release_date).
    - Can you recommend a movie to me? I'm in the mood for a [horror](genre) movie and would love to see [Johnny Depp](cast) in it. It should have been released in [2020](release_date).
- intent: movie_genre+movie_producer
  examples: |
    - If you don't mind, could you provide me with the genre and producer of [Saw V](movie_name)?
    - Would you mind sharing the genre and producer of [The Terminator](movie_name) with me?
    - I'm not sure about the genre and producer of [Scream](movie_name). Could you help me out?
    - I'm curious about [Saving private Ryan](movie_name). Can you tell me its genre and producer?
- intent: greetings
  examples: |
    - good afternoon
    - howdy
    - hello there
    - let's go
    - Hello there
- intent: is_after
  examples: |
    - [After this year's end](movie_period)
    - [Following the end of the year's](movie_period) cycle.
    - [Beyond the current year](movie_period)
    - If possible, [following this year](movie_period)
- intent: is_before
  examples: |
    - If it can be done, [prior](movie_period) to this year
    - [Before](movie_period)
    - [Earlier than](movie_period) the present year
    - [Before](movie_period) the onset of this year
- intent: just_rating+just_director
  examples: |
    - [10](rating). Furthermore, is there a chance that I could recommend [Martin Scorsese](director_name) to direct it?
    - [9](rating). Moreover, may I raise the question of considering [Martin Scorsese](director_name) as the director for it?
    - [1](rating) and [Yorgos Lanthimos](director_name) if possible.
    - [five](rating) or so. And can I request [Wes Anderson](director_name) as the director for it?
    - [ten](rating) and [Spike Lee](director_name) as the director.
- intent: is_exactly
  examples: |
    - [Within the confines of this year](movie_period), if possible
    - If achievable, [in the present year](movie_period)
    - If attainable, [during this year](movie_period)
    - If it is possible, [in the current year](movie_period)
    - If doable, [in this year](movie_period)
- intent: deny
  examples: |
    - no, I'm fine
    - I'm done
    - no way
    - Noo
    - no, thanks
    - no i'm fine
- intent: ask_recommendation_without_movie
  examples: |
    - I'm looking for a movie that's not too heavy, can you recommend one?
    - Can you give me a movie recommendation?
    - Do you have any recommendations for a movie to watch?
    - recommend a movie
    - Could you suggest a movie that's based on a true story?
    - What's a good movie you'd recommend?
- intent: affirm
  examples: |
    - Sure thing!
    - That sounds perfect!
    - Certainly!
    - Without a doubt!
    - Yes, please!
    - yes please
    - that's right
    - all good
- intent: just_genre+just_cast+just_year
  examples: |
    - [Historical](genre). I would also like to have [Denzel Washington](cast) as an actor, and I would like the movie to be released in [2007](release_date).
    - [Mystery](genre) suspense. I would love to see [Emma Stone](cast) in a mysterious role, and I prefer the movie to be released in [2010](release_date).
    - I'm in the mood for a [horror](genre) film, if it's possible to find one. It would be fantastic to have [Brad Pitt](cast) as the actor. Additionally, can the movie be released in [2020](release_date)?
    - [Romantic comedy](genre). I would also like to have [Jennifer Lawrence](cast) as an actress, and I would like the movie to be released in [2005](release_date).
    - [Sci-fi thriller](genre). It would be great if [Tom Hanks](cast) is part of the cast, and I prefer the movie to be released in [2021](release_date).
    - [Science fiction](genre). I would also like to have [Anne Hathaway](cast) as an actress, and I would like the movie to be released in [2013](release_date).
    - [Supernatural](genre). I would also like to have [Johnny Depp](cast) as an actor, and I would like the movie to be released in [2006](release_date).
- intent: movie_rating
  examples: |
    - I'm wondering, how well was [Avengers: Endgame(movie_name) received?
    - What is the movie's overall rating?
    - Could you tell me how [Star Wars: A New Hope](movie_name) was received?
    - Do you know what people think of [The Dark Knight](movie_name)?
    - What was the impact of the movie's rating on its overall success or reception?
    - How did audiences and critics rate [Forrest Gump](movie_name)?
    - Can you inform me of the rating of [The Lion King](movie_name)?
    - How did audiences and critics rate [The Silence of the Lambs](movie_name)?
    - How did the movie's rating influence its distribution and release?
- intent: movie_runtime
  examples: |
    - Can you give me the duration of [Indiana Jones and the Raiders of the Lost Ark](movie_name)?
    - I'm curious, what's the duration of [Jurassic Park](movie_name)?
    - its runtime
    - How much time does the movie require?
    - Can you inform me of the duration of [The Silence of the Lambs](movie_name)?
    - What is the running time of the movie?
    - How long is the movie from beginning to end?
    - and what about the runtime?
- intent: movie_revenue
  examples: |
    - Can you give me the financial performance of [Indiana Jones and the Kingdom of the Crystal Skull](movie_name)?
    - What was the movie's profit margin?
    - What was the total revenue for [The Lion King](movie_name)?
    - How much profit did the movie make?
    - How much money did [The Lord of the Rings: The Return of the King](movie_name) make in theaters?
    - How much did [The Exorcist](movie_name) make at the box office?
    - Can you give me some details about the movie's financial performance?
    - its revenue
    - What was the box office revenue for [Avatar](movie_name)?
- intent: out_of_scope
  examples: |
    - Can you recommend a good hiking trail?
    - Can you translate this sentence into Spanish?
    - Can you recommend a good restaurant nearby?
    - Can you help me with my math homework?
    - How do I start my own business?
    - What's the capital of Australia?
    - What's the best way to lose weight?
    - How do I bake a chocolate cake?
- intent: ask_recommendation_with_movie
  examples: |
    - After watching [The Dark Knight](movie_name), what other movies would you suggest?
    - What other movies would you suggest if I enjoyed watching [Fight Club](movie_name)?
    - I recently watched [No Country for Old Men](movie_name), do you know any movies that are similar?
    - What other movies would you suggest if I enjoyed watching [The Social Network](movie_name)?
    - I just saw [The Matrix](movie_name), do you have any similar movie recommendations?
    - Do you have any movie recommendations similar to [The Departed](movie_name)?
    - Do you have any movie recommendations similar to [The Silence of the Lambs](movie_name)?
    - I really enjoyed [Full Metal Jacket](movie_name), can you suggest a similar movie to watch?
    - After seeing [The Exorcist](movie_name), can you recommend a similar movie to watch?
- intent: goodbye
  examples: |
    - bye bye
    - That's fine, goodbye for now.
    - No worries, catch you later.
    - Agreed, talk to you later.
    - Okay then, talk to you soon.
    - goodbye
    - No problem, bye for now.
    - Understood, bye for now.
- intent: just_genre
  examples: |
    - [Historical](genre) and [Drama](genre)
    - [fantasy](genre)
    - [tv movie](genre), [Horror](genre) and also [Comedy](genre)
    - [Fantasy](genre) with some elements of [Adventure](genre)
    - [horror](genre) please
    - [drama](genre)
    - [Superhero](genre) with [Action](genre)
    - [documentary](genre)
    - [Documentary](genre) together with [Crime](genre)
- intent: just_year
  examples: |
    - [2001](release_date)
    - [2002](release_date)
    - [1993](release_date)
    - [1992](release_date)
    - [2004](release_date)
    - [2023](release_date)
    - [1987](release_date)
    - [1997](release_date)
    - [2019](release_date)
- intent: ask_movie_question
  examples: |
    - I'd like to ask some questions that are related to the world of movies.
    - What sorts of inquiries can I pose?
    - What are the acceptable question formats?
    - What parameters define the questions I can ask?
    - What are the permissible question types?
    - I'm hoping to ask questions specifically about movies.
    - Are there any specific question categories I should adhere to?
    - I have some movie-related questions that I'd like to ask.
    - I want to pick your brain about movies by asking some questions.
    - I have a few inquiries about movies that I'd like to make.
    - Are there any limitations on the subject matter of the questions?
- intent: movie_budget
  examples: |
    - Can you tell me the budget for [Gone with the Wind](movie_name)?
    - How much did [E.T. the Extra-Terrestrial](movie_name) cost to make?
    - Can you tell me the budget for [Forrest Gump](movie_name)?
    - Can you tell me the production budget for [The Avengers](movie_name)?
    - Do you happen to know what the budget for [Jurassic Park](movie_name) was?
    - What was the budget for [The Incredibles](movie_name)?
    - How much money was spent on the movie?
    - What was the total budget for [Rocky](movie_name)?
    - Do you happen to know how much [Avatar](movie_name) cost to produce?
    - What was the total budget for [Indiana Jones and the Raiders of the Lost Ark](movie_name)?
    - Can you tell me about any significant financial decisions made during the movie's production?
- intent: movie_composer
  examples: |
    - Who is the composer of [The Grand Budapest Hotel](movie_name)?
    - Who was in charge of composing the movie's music?
    - [Ghostbusters](movie_name), who was the composer of this film?
    - its composer
    - Who was involved in composing the movie's score?
    - [The Good, the Bad and the Ugly](movie_name), who was the composer of this film?
    - Who composed the music for [The Lion King](movie_name)?
    - Who composed the music for [Jaws](movie_name)?
    - Can you tell me who is the composer of [The Avengers](movie_name)?
    - and what about the composer?
    - Can you give me some information about the music created specifically for the movie?
    - Who is credited with creating the movie's music?
    - Who composed the music for [Inception](movie_name)?
- intent: ask_movie_with_similar_plot
  examples: |
    - Are you able to recommend a movie if I tell you the plot?
    - May I describe a plot and you find a movie with a similar one?
    - Could you assist me in locating a film with a plot similar to the one I'm describing?
    - Can you help me find a movie with a similar plot to the one I'm about to describe?
    - Would you be able to suggest a movie that fits a plot I provide?
    - Could you suggest a movie that matches the plot I have in mind?
    - Could you recommend a movie based on a plot I tell you?
    - I have a plot in mind, could you suggest a movie that fits it?
    - Can you help me find a movie with a storyline that's similar to the plot I'm about to describe?
    - Is there a chance you could suggest a movie with a plot similar to the one I'm describing?
    - Can you recommend a movie that matches a plot I have in mind?
    - Would you be able to suggest a movie with a plot similar to the one I'm describing?
- intent: just_cast
  examples: |
    - [Kevin Spacey](cast)
    - [Meryl Streep](cast) and [Johnny Depp](cast)
    - [Cameron Diaz](cast)
    - [Eddie Murphy](cast)
    - [Scarlett Johansson](cast)
    - [Gwyneth Paltrow](cast)
    - [Idris Elba](cast)
    - [Anthony Hopkins](cast)
    - [Will Smith](cast)
    - [Jodie Foster](cast)
    - [Oprah Winfrey](cast)
    - [James Cameron](cast) and [Arnold Schwarzenegger](cast)
    - [Anne Hathaway](cast)
- intent: movie_producer
  examples: |
    - Can you find out who produced [The Great Gatsby](movie_name)?
    - Who put together the movie's production team?
    - I'm curious, who produced [Gone with the Wind](movie_name)?
    - Can you tell me who produced [Back to the Future](movie_name)?
    - Who produced [Apocalypse Now](movie_name)?
    - its producer
    - Can you tell me who produced [Alien](movie_name)?
    - Who was the producer of [The Usual Suspects](movie_name)?
    - Can you give me some information about the production of the movie?
    - I'm curious, who produced [The Elephant Man](movie_name)?
    - Can you find out who produced [The Silence of the Lambs](movie_name)?
    - What is the name of the movie's producer?
    - Can you find out who produced [The Shining](movie_name)?
- intent: just_director
  examples: |
    - [Martin Scorsese](director_name)
    - [Oliver Stone](director_name)
    - [Terry Gilliam](director_name) and [Christian Bale](director_name)
    - [Martin Scorsese](director_name) and [Robert De Niro](director_name)
    - [Joe Russo](director_name)
    - [Jane Campion](director_name)
    - [Darren Aronofsky](director_name)
    - [Bernardo Bertolucci](director_name)
    - [Sergio Leone](director_name)
    - [Guy Ritchie](director_name)
    - [George Lucas](director_name)
    - [Woody Allen](director_name)
    - [Billy Wilder](director_name)
    - [Alejandro González Iñárritu](director_name)
- intent: movie_plot
  examples: |
    - Can you tell me the plot of [Star Wars: Episode IV - A New Hope](movie_name)?
    - What is [The Lord of the Rings: The Two Towers](movie_name) about?
    - What is [Goodfellas](movie_name) about?
    - What is [Titanic](movie_name) about?
    - What is the movie's storyline?
    - Can you tell me the plot of [The Prestige](movie_name)?
    - [The Sixth Sense](movie_name), can you describe the plot of this movie?
    - What is [The Dark Knight Rises](movie_name) about?
    - Can you tell me the storyline of [Indiana Jones and the Raiders of the Lost Ark](movie_name)?
    - [The Princess Bride](movie_name), can you describe the plot of this movie?
    - [Gladiator](movie_name), can you describe the plot of this movie?
    - What is the movie's primary plot?
    - What is the movie about?
    - [The Lord of the Rings: The Fellowship of the Ring](movie_name), can you describe the plot of this movie?
- intent: movie_release_date
  examples: |
    - [Indiana Jones and the Raiders of the Lost Ark](movie_name), when was this movie released?
    - and what about the release date?
    - Can you tell me when [The Shining](movie_name) premiered?
    - What date did the movie come out?
    - Can you tell me when [The Silence of the Lambs](movie_name) was released?
    - When did the movie hit theaters?
    - What is the release date of [The Green Mile](movie_name)?
    - Can you tell me the release date of [Gladiator](movie_name)?
    - [The Princess Bride](movie_name), can you tell me the premiere date of this movie?
    - When did [Jaws](movie_name) come out?
    - When did [The Lord of the Rings: The Two Towers](movie_name) come out?
    - [Titanic](movie_name), when was this movie released?
    - When was [The Matrix](movie_name) released?
    - When was [The Godfather: Part II](movie_name) released?
- intent: movie_genre
  examples: |
    - Would you classify [Gone with the Wind](movie_name) as a [drama](genre) or a [romance](genre) movie?
    - Can you tell me the genre of [The Incredibles](movie_name)?
    - What genre would you classify [The Shawshank Redemption](movie_name) as?
    - Would you classify [Aladdin](movie_name) as a [romance](genre) or an [adventure](genre) movie?
    - Can you tell me the genre of [The Godfather](movie_name)?
    - How would you categorize [Wreck-It Ralph](movie_name) in terms of genre?
    - What genre would you classify [Ghostbusters](movie_name) as?
    - What genre does the movie fall into?
    - Nice, thank you! can you tell me also about its genre?
    - Do you happen to know the genre of [The Dark Knight](movie_name)?
    - What kind of movie is it?
    - I'm wondering, what genre does [The Lion King](movie_name) belong to?
    - What would you classify [Toy Story](movie_name) as?
    - Can you give me an idea of the genre of [Indiana Jones and the Raiders of the Lost Ark](movie_name)?
- intent: movie_director
  examples: |
    - Who was the director of [The Silence](movie_name)?
    - [The Godfather](movie_name), who was the director of this film?
    - Can you tell me who directed [The Exorcist](movie_name)?
    - Who helmed the movie's direction?
    - What is the director's name?
    - Who directed [A Beautiful Mind](movie_name)?
    - Who oversaw the movie's direction and production?
    - Can you tell me who directed [The Breakfast Club](movie_name)?
    - Who had creative control over the movie's direction?
    - Who was the director of [The Graduate](movie_name)?
    - Who is the director of the movie?
    - Who directed [Psycho](movie_name)?
    - Who was the director of [The Truman Show](movie_name)?
    - Who directed [Goodfellas](movie_name)?
    - Can you tell me who directed [Back to the Future](movie_name)?
- intent: movie_cast
  examples: |
    - Who was responsible for casting the actors in the movie?
    - Who are the actors in [The Silence of the Lambs](movie_name)?
    - Can you give me a rundown of [three](number_of_actors) actors who appeared in the movie?
    - Who are the actors in [The Sixth Sense](movie_name)?
    - Who are the actors in [The Breakfast Club](movie_name)?
    - Who are the people behind the movie's performances?
    - Can you name some of the actors in [Gladiator](movie_name)?
    - Would you mind sharing the names of [12](number_of_actors) actors who played roles in the movie?
    - Who collaborated with the actors in the movie's production?
    - Can you tell me who stars in [The Matrix](movie_name)?
    - Who stars in [Jaws](movie_name)?
    - [Star Wars: Episode IV - A New Hope](movie_name), who are the actors in this movie?
    - Would you be able to tell me the names of [four](number_of_actors) actors that played roles in the movie?
    - Can you tell me who stars in [The Shining](movie_name)?
    - Who are the actors in [Fight Club](movie_name)?
    - [The Silence of the Lambs](movie_name), who is in the cast of this movie?
    - Can you tell me who stars in [The Truman Show](movie_name)?
    - Who is part of the cast in [Titanic](movie_name)?
    - [The Lord of the Rings: The Two Towers](movie_name), who stars in this movie?
- synonym: '1'
  examples: |
    - one
    - One
- synonym: '2'
  examples: |
    - two
    - Two
- synonym: '3'
  examples: |
    - three
    - Three
- synonym: '4'
  examples: |
    - four
    - Four
- synonym: '5'
  examples: |
    - five
    - Five
- synonym: '6'
  examples: |
    - six
    - Six
- synonym: '7'
  examples: |
    - seven
    - Seven
- synonym: '8'
  examples: |
    - eight
    - Eight
- synonym: '9'
  examples: |
    - nine
    - Nine
- synonym: '10'
  examples: |
    - ten
    - Ten
- synonym: horror
  examples: |
    - scary
- synonym: comedy
  examples: |
    - funny
